### ISSUE TITLE
Feature/aergocli cluster remove bug

### ISSUE THREAD

**Issue by kslee8282** [aergoio/aergo#129]
**SIGSEGV occurred after attempting to remove the cluster with aergocli.**

```
aergo_bp1@aergo_bp1:/blockchain/raft_local$ ./aergocli getconsensusinfo | jq
{
  "Type": "raft",
  "Info": {
    "Leader": "local3",
    "Total": 3,
    "Name": "local1",
    "RaftId": "87adff9d674ad15a",
    "Status": {
      "id": "87adff9d674ad15a",
      "term": 7,
      "vote": "5019815a18b608cb",
      "commit": 87646,
      "lead": "5019815a18b608cb",
      "raftState": "StateFollower",
      "applied": 87646,
      "progress": {},
      "leadtransferee": "0"
    }
  },
  "Bps": [
    {
      "Name": "local1",
      "RaftID": "87adff9d674ad15a",
      "PeerID": "16Uiu2HAkzuBCPFPQuBjHq5g8KDrACXdZ8NC6qHKJ15QCQM6bWeSf",
      "Addr": "/ip4/192.168.1.231/tcp/7846"
    },
    {
      "Name": "local2",
      "RaftID": "b4eb7ceaeda0a971",
      "PeerID": "16Uiu2HAmRM3cvKN1HVGMbPeCCbXQfAiF9dH5ZXLvsh7MEuLjjqXF",
      "Addr": "/ip4/192.168.1.242/tcp/7846"
    },
    {
      "Name": "local3",
      "RaftID": "5019815a18b608cb",
      "PeerID": "16Uiu2HAm7xYuxydz39E6jq4mG5p9ttzCuPKwsvdmsNN5nPGhLeTc",
      "Addr": "/ip4/192.168.1.243/tcp/7846"
    }
  ]
}

./aergocli cluster remove --nodeid 5019815a18b608cb
Failed to remove member: rpc error: code = Unknown desc = failed to change membership: this node is not leader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb8eb4a]
goroutine 1 [running]:
github.com/aergoio/aergo/cmd/aergocli/cmd.glob..func11(0x17eaa60, 0xc0002b1440, 0x0, 0x2)
        /home/travis/gopath/src/github.com/aergoio/aergo/cmd/aergocli/cmd/cluster.go:91 +0x12a
github.com/spf13/cobra.(*Command).execute(0x17eaa60, 0xc0002b13e0, 0x2, 0x2, 0x17eaa60, 0xc0002b13e0)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x17ecfe0, 0x0, 0x0, 0xb91e7d)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
        /home/travis/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/aergoio/aergo/cmd/aergocli/cmd.Execute()
        /home/travis/gopath/src/github.com/aergoio/aergo/cmd/aergocli/cmd/root.go:114 +0x3d
main.main()
        /home/travis/gopath/src/github.com/aergoio/aergo/cmd/aergocli/aergocli.go:14 +0x20
```

**And is a non-admin user a cluster-removable command?**

```
./aergocli cluster remove --help
Remove raft node with given node id from cluster. This command can only be used for raft consensus.
Usage:
  aergocli cluster remove [flags]

Flags:
  -h, --help            help for remove
      --nodeid string   node id to remove to the cluster
[ADMIN EMPTY]


```

**Comment by eve2adam** [comment]
cli cluster command removed at https://github.com/aergoio/aergo/tree/hotfix/2.2.2
