### ISSUE TITLE
[contract] system down: 'contract.call' with unparseable 'address'

### ISSUE THREAD

**Issue by hanlsin** [aergoio/aergo#20]
```
panic: runtime error: slice bounds out of range

goroutine 217 [running, locked to thread]:
github.com/aergoio/aergo/vendor/github.com/anaskhan96/base58check.Decode(0x0, 0x0, 0xc0001cd0f8, 0x47437eb, 0x8840448, 0x0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/vendor/github.com/anaskhan96/base58check/base58check.go:72 +0x4c1
github.com/aergoio/aergo/types.DecodeAddress(0x0, 0x0, 0x0, 0x4073c82, 0x0, 0xc0000ba008, 0xc0001cd198)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/types/account.go:52 +0x39
github.com/aergoio/aergo/contract.LuaCallContract(0x8840378, 0xc00b4f5364, 0x8840448, 0x884a438, 0x6208130, 0x0, 0x0, 0x0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/contract/vm_callback.go:90 +0xee
github.com/aergoio/aergo/contract._cgoexpwrap_82f79b750651_LuaCallContract(0x8840378, 0xc00b4f5364, 0x8840448, 0x884a438, 0x6208130, 0x0, 0x0, 0x6208130)
        _cgo_gotypes.go:1522 +0x6a
github.com/aergoio/aergo/contract._Cfunc_vm_pcall(0x8840378, 0x1, 0xc0000ac7bc, 0x0)
        _cgo_gotypes.go:1347 +0x4e
github.com/aergoio/aergo/contract.(*Executor).call.func3(0x8840378, 0xc000000001, 0xc0000ac7bc, 0xc0001c7380)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/contract/vm.go:269 +0x68
github.com/aergoio/aergo/contract.(*Executor).call(0xc00b4cf2c0, 0xc00b4fee10, 0x0, 0xc00b4f5300)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/contract/vm.go:269 +0xf5
github.com/aergoio/aergo/contract.Call(0xc00b4cf220, 0xc00b59ef60, 0x28, 0x30, 0xc00b59ef30, 0x21, 0x30, 0xc00b4f5300, 0x0, 0x0, ...)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/contract/vm.go:419 +0x1d0
github.com/aergoio/aergo/contract.Execute(0xc0002f0990, 0xc000141c80, 0x2b35, 0x156ff91232cd4f48, 0xc00b53c360, 0xc00b53c3c0, 0x0, 0x80571d02481c690f, 0x66dc9834156bbadf, 0xb75bf11e75527a7, ...)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/contract/contract.go:103 +0x9d1
github.com/aergoio/aergo/chain.executeTx(0xc0002f0990, 0xc000141c80, 0x2b35, 0x156ff91232cd4f48, 0x0, 0x479a165, 0xc0001361b0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/chain/chainhandle.go:558 +0x1146
github.com/aergoio/aergo/chain.NewTxExecutor.func1(0xc0002f0990, 0xc000141c80, 0x0, 0x0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/chain/chainhandle.go:430 +0x9c
github.com/aergoio/aergo/consensus/impl/sbp.(*txExec).Apply(0xc0000ba538, 0xc0002f0990, 0xc000141c80, 0x0, 0x0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/impl/sbp/sbp.go:42 +0x3d
github.com/aergoio/aergo/consensus/chain.NewCompTxOp.func1(0xc0002f0990, 0xc000141c80, 0xc0001d8800, 0x10)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/tx.go:63 +0x75
github.com/aergoio/aergo/consensus/chain.TxOpFn.Apply(0xc00b5d23c0, 0xc0002f0990, 0xc000141c80, 0x0, 0xc0001cdce0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/tx.go:55 +0x3a
github.com/aergoio/aergo/consensus/chain.NewCompTxOp.func1(0xc0002f0990, 0xc000141c80, 0x4ce17c0, 0xc00b50a7a0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/tx.go:63 +0x75
github.com/aergoio/aergo/consensus/chain.TxOpFn.Apply(0xc00b50a7a0, 0xc0002f0990, 0xc000141c80, 0x5043960, 0xc00b50a7a0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/tx.go:55 +0x3a
github.com/aergoio/aergo/consensus/chain.GatherTXs(0x5041d00, 0xc0001fc780, 0xc0002f0990, 0x5043960, 0xc00b5d23c0, 0x100000, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/tx.go:132 +0x32c
github.com/aergoio/aergo/consensus/chain.GenerateBlock(0x5041d00, 0xc0001fc780, 0xc0000c99a0, 0xc0002f0990, 0x5043960, 0xc00b5d23c0, 0x156ff91232cd4f48, 0xc0000c99a0, 0x0, 0x0)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/chain/block.go:67 +0x80
github.com/aergoio/aergo/consensus/impl/sbp.(*SimpleBlockFactory).Start(0xc0001fc780)
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/impl/sbp/sbp.go:170 +0x315
created by github.com/aergoio/aergo/consensus.Start
        /Users/yp/work/blocko/go/src/github.com/aergoio/aergo/consensus/consensus.go:99 +0x74
```

**Comment by eve2adam** [comment]
committed da2ac3c8d77919c1edf01a8af19cbc95eaccf881
